### ISSUE TITLE
[nltk_data] Error

### ISSUE THREAD

**Issue by joeyclancy** [a-h-b/binny#37]
Hello, dear binny support team
  something went wrong when I run './binny -i config/config.init.yaml':

> Preparing NLP Resources!
[nltk_data] Error loading stopwords: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading universal_tagset: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
[nltk_data] Error loading wordnet: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
[nltk_data] Error loading omw-1.4: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
Finished setting up databases!
This Assembler process finished running at 2022-09-30 16:11:15 and took 2 seconds to complete.

the nltk_data directory was set manually, and all resource are in ~/nltk_data/taggers.
the snakemake and prokka was set previously in a conda env, and the 'my_conda_env_path' and 'my_mantis_env' path was set by defalut.

Could you please help me check what is the reason?

sincerely
Joey
<img width="286" alt="截屏2022-09-30 16 51 57" src="https://user-images.githubusercontent.com/70930319/193232740-e9a9cd54-8fc3-4ad2-aab2-5eaecc351f39.png">

**Comment by PedroMTQ** [comment]
Hello @joeyclancy 

This error comes from NLTK, which is connected to binny in the following manner:
nltk -> unifunc -> mantis -> binny

I tried downloading the nltk resources, and atm it appears to be working, but maybe at the moment you tried, the servers were down? If this issue keeps occurring, the issue may be different; UniFunc always tries to download NLTK resources, if they have already been downloaded an exception is raised, please see below:
https://github.com/PedroMTQ/UniFunc/blob/main/unifunc/source.py @`def download_nltk_resources`

It could be that changing the path of nltk resources raises some issues in this method, but you could to experiment with leaving it as default.

From your image, it looks like the files are downloaded, so I'm not sure why that connection issue is being raised. Does you system have any connection restraints in place?
After a quick google search I found a few solutions propositions:
https://stackoverflow.com/questions/27750608/error-installing-nltk-supporting-packages-nltk-download


In any case, please try to run from a python console:
`
from nltk.corpus import stopwords
stopwords.words("english")
`

Check if the import is performed. If so, then NLTK is able to find the data and you could probably just ignore that warning.


Regards,
Pedro

**Comment by joeyclancy** [comment]
<img width="649" alt="截屏2022-09-30 17 40 26" src="https://user-images.githubusercontent.com/70930319/193242225-07d93fcb-1d67-4d32-9b4b-de77fb476b2e.png">

  Thanks Pedro, I thinks it works in python console, and I cann't wait to try test './binny -l -n "TESTRUN" -r config/config.test.yaml'. Sadlly, there is error occuring:

<img width="1250" alt="截屏2022-09-30 17 51 47" src="https://user-images.githubusercontent.com/70930319/193245311-0f218344-6f59-492f-837e-b804c9f947a4.png">

**Comment by PedroMTQ** [comment]
@ohickl I think this is your cue

**Comment by ohickl** [comment]
Hi Joey,
deleting the `test_output` dir and rerunning the test should fix the `IncompleteFilesException` error. I am unsure why you also seem to have trouble with the binny conda env. Can you activate `.../anaconda3/envs/binny` without any problems? Lets us now, how it went.

Best,
Oskar

**Comment by joeyclancy** [comment]
> @ohickl I think this is your cue
Thanks for your time, Pedro

**Comment by ohickl** [comment]
`Reason: Missing output files...` is just Snakemake determining that it needs to run a rule to create its output, as it is not there yet. Its working as intended. 

Strange that you are still getting the same error. Could you post the entire log again, so I can have a look?

**Comment by joeyclancy** [comment]
Thanks, Oskar. The conda env is '/public/home/hymeta/anaconda3/envs/binny' when I run './binny -l -n "TESTRUN" -r config/config.test.yaml'. The 'my_conda_env_path' and 'my_mantis_env' was set by default; 'my_prokka_env' and 'my_snakemake_env' were changed path to the conda env '/public/home/hymeta/anaconda3/envs/binny'. The entire log is posted below:
<img width="1437" alt="截屏2022-09-30 21 50 59" src="https://user-images.githubusercontent.com/70930319/193286397-b9ea8d19-02ca-476e-9ead-fbd6bce7bd1e.png">
<img width="1439" alt="截屏2022-09-30 21 51 32" src="https://user-images.githubusercontent.com/70930319/193286407-1586d0de-e208-4bc1-a69f-9252fb0c9e51.png">
<img width="1153" alt="截屏2022-09-30 21 51 48" src="https://user-images.githubusercontent.com/70930319/193286420-6bbd09bd-1746-4133-966f-4d9fe2183042.png">

**Comment by ohickl** [comment]
Thanks. 
So you created a conda env `binny` that contains Snakemake and Prokka? If so, what was the reason for that? Might be perfectly fine though, just curious. The option to pass your own environments to binny is meant to allow the reuse of existing (Prokka/Snakemake) envs, to reduce duplication of tools. If you are going to create them from scratch anyway, I would leave it at the defaults to minimize the risk for unexpected interactions.
I think, the problem lies with that environment/the activation of that environment, still. It fails to properly activate it when trying to run the Prokka rule. Could you try to run `conda config --set channel-priority strict`, as suggested by Snakemake at the start of the log and try again? It could be that this somehow messes with Snakemakes ability to properly activate the envs.

**Comment by joeyclancy** [comment]
Thank you, Oskar. If  snakemake path is default, there will be another error :

> Creating snakemake environment
/public/home/hymeta/Tools/binny/conda/snakemake_env/lib/pypy3.8/site-packages/google/protobuf/internal/api_implementation.py:95: UserWarning: PyPy does not work yet with cpp protocol buffers. Falling back to the python implementation.
  warnings.warn('PyPy does not work yet with cpp protocol buffers. '

Now I set Prokka env as default path, and I get new error ('conda config --set channel-priority strict' have been ran, however, still got the cue)
<img width="1438" alt="截屏2022-10-01 00 32 43" src="https://user-images.githubusercontent.com/70930319/193320955-d9967407-a534-487d-b357-941952d87646.png">
<img width="1424" alt="截屏2022-10-01 00 33 01" src="https://user-images.githubusercontent.com/70930319/193320971-43dbed1e-0c58-48a2-a47e-3240d3dfcc01.png">
<img width="1428" alt="截屏2022-10-01 00 33 13" src="https://user-images.githubusercontent.com/70930319/193320978-c1933174-4280-47a5-8582-3fdff08b13aa.png">

**Comment by ohickl** [comment]
Yes, there unfortunately is an issue with HDBSCAN and joblib at the moment. Hopefully they will fix it soon. In the meantime you could try what I suggested [here](https://github.com/a-h-b/binny/issues/38#issuecomment-1264308976) in #38.
Sorry for the inconvenience.

**Comment by joeyclancy** [comment]
Thank you, Oska, it is very helpful. The test program run well, and I got 4 bins and binny.done in test_output dir, though there still has errors occured:
`[Sat Oct  1 20:28:34 2022]
Finished job 0.
9 of 9 steps (100%) done
Complete log: ../.snakemake/log/2022-10-01T195833.168819.snakemake.log
Config file /public/home/hymeta/Tools/binny_env/config/config.default.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Creating report...
Loading script code for rule binny
Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2ab73fd30e90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ab73fd30e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/__init__.py", line 815, in snakemake
    containerize=containerize,
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/workflow.py", line 864, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/__init__.py", line 859, in auto_report
    packages = data.get_packages()
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/data/packages.py", line 19, in get_packages
    license_url="https://raw.githubusercontent.com/snakemake/snakemake/main/LICENSE.md",
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/data/packages.py", line 75, in __init__
    self.license = get_resource_as_string(license_url)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/data/common.py", line 12, in get_resource_as_string
    r = requests.get(path_or_uri)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ab73fd30e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Should it be concerned?

**Comment by joeyclancy** [comment]
Hi Oskar
 Your comment is very helpful. Now I got 4 bins and binny.done in test_output dir successfully, while some errors still ouccured, seems there are conflicts between binny and ../anaconda3/env/binny:

> `[Sat Oct  1 20:28:34 2022]
localrule ALL:
    input: /public/home/hymeta/Tools/binny_env/test_output/binny.done
    jobid: 0
    reason: Input files updated by another job: /public/home/hymeta/Tools/binny_env/test_output/binny.done
    resources: tmpdir=/tmp

[Sat Oct  1 20:28:34 2022]
Finished job 0.
9 of 9 steps (100%) done
Complete log: ../.snakemake/log/2022-10-01T195833.168819.snakemake.log
Config file /public/home/hymeta/Tools/binny_env/config/config.default.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Creating report...
Loading script code for rule binny
Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2ab73fd30e90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ab73fd30e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/__init__.py", line 815, in snakemake
    containerize=containerize,
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/workflow.py", line 864, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/__init__.py", line 859, in auto_report
    packages = data.get_packages()
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/data/packages.py", line 19, in get_packages
    license_url="https://raw.githubusercontent.com/snakemake/snakemake/main/LICENSE.md",
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/data/packages.py", line 75, in __init__
    self.license = get_resource_as_string(license_url)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/snakemake/report/data/common.py", line 12, in get_resource_as_string
    r = requests.get(path_or_uri)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/public/home/hymeta/anaconda3/envs/binny/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2ab73fd30e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Should it be concerned?

Sincerely
Joey

**Comment by joeyclancy** [comment]
Hi, I use my metagenomic data for binning without errors, and I install binny in other HPC succesefully. The results seems good for me. Thanks for help and the wonderful binny!

**Comment by ohickl** [comment]
Great to hear and thanks for your interest!
