### ISSUE TITLE
Trying to produce bins

### ISSUE THREAD

**Issue by jp589** [a-h-b/binny#41]
Hello,

I previously raised an issue about the test run and we fixed that in issue #38. However, with my real data I have run into new issues. This time, with four samples I am able to go through the entire process and get a bins directory in the output folder, but no bins.

My first thought was to reduce the minimum completeness and purity to around 70 each. However, I still didn't get any bins. My next thought was that perhaps I needed to add more samples so I used all of them, which in total was nearly 3000. However, I have run into a different issue. I am able to get through all steps except for the final binning_binny step. I have posted the config files I'm using config.mod_default.yaml and slurm_simple.config.yaml, as well as VARIABLE_CONFIG and the output from binny.binny..stdout, binning_binny.log, and the slurm output file. 

The binny secondary job was running on one node with 11 CPU and 100Gb RAM for each CPU resulting in 1.1Tb of RAM.

Just need help pinpointing the problem so that I can get bins from this metagenomic data.

Thanks,

jp589

binny.binny..stdout:

```Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 11
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Wed Nov  2 08:54:14 2022]
Job 0: binny: Running Python Binny.

Activating conda environment: /home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e
Activating conda environment: /home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1113, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array data from dtype('O') to dtype('float32') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/binny_output/.snakemake/scripts/tmpr3yfilst.binny_main.py", line 157, in <module>
    all_good_bins, contig_data_df_org, min_purity = iterative_embedding(x_contigs, depth_dict, all_good_bins, starting_completeness,
  File "/home/binny/workflow/scripts/binny_functions.py", line 1586, in iterative_embedding
    contig_data_df = load_and_merge_cont_data(annot_file, mg_depth_file, coord_df, dims=n_dim,
  File "/home/binny/workflow/scripts/binny_functions.py", line 98, in load_and_merge_cont_data
    depth_df = pd.read_csv(depth_file, sep='\t', low_memory=False, names=depth_cols, dtype=depth_dtype_dict)
  File "/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1250, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 787, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 883, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1026, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1119, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: 'contigLen'
[Wed Nov  2 11:38:25 2022]
Error in rule binny:
    jobid: 0
    output: /home/binny_output/binny.done
    log: /home/binny_output/logs/binning_binny.log (check log file(s) for error message)
    conda-env: /home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e

Traceback (most recent call last):
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/binny/conda/snakemake_env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2460, in run_wrapper
    raise ex
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
    run(
  File "/home/binny/Snakefile", line 668, in __rule_binny
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 1369, in script
    executor.evaluate()
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 582, in execute_script
    self._execute_cmd("{py_exec} {fname:q}", py_exec=py_exec, fname=fname)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 414, in _execute_cmd
    return shell(
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /home/binny/conda/snakemake_env/bin/activate '/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e'; set -euo pipefail;  python /home/binny_output/.snakemake/scripts/tmpr3yfilst.binny_main.py' returned non-zero exit status 1.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message`
```

binning_binny.log:

```02/11/2022 08:54:36 AM - Starting Binny run for sample test_10_31_22.
02/11/2022 08:55:04 AM - Looking for single contig bins.
02/11/2022 08:55:17 AM - Found 0 single contig bins.
02/11/2022 08:55:17 AM - Calculating N90
02/11/2022 08:55:19 AM - N90 is 541, with scMAGs would be 541.
02/11/2022 08:55:26 AM - Masking potentially disruptive sequences from k-mer counting.
02/11/2022 08:55:29 AM - Calculating k-mer frequencies of sizes: 2, 3, 4.
02/11/2022 09:00:14 AM - K-mer frequency matrix created in 287s.
02/11/2022 09:36:44 AM - Using coassembly mode.
02/11/2022 09:36:48 AM - Running with 1458430 contigs. Filtered 0 contigs using a min contig size of 500 to stay below 1500000.0 contigs
02/11/2022 09:37:34 AM - Running manifold learning and dimensionality-reduction.
02/11/2022 09:40:06 AM - Initializing embedding.
02/11/2022 09:46:09 AM - EE iteration 125 - KLD: 10.3596
02/11/2022 09:48:22 AM - EE iteration 250 - KLD: 10.3581, KLDRC: 0.02%
02/11/2022 09:50:35 AM - EE iteration 375 - KLD: 9.9519, KLDRC: 3.92%
02/11/2022 09:52:49 AM - EE iteration 500 - KLD: 9.1015, KLDRC: 8.54%
02/11/2022 09:55:03 AM - EE iteration 625 - KLD: 8.7002, KLDRC: 4.41%
02/11/2022 09:57:16 AM - EE iteration 750 - KLD: 8.4611, KLDRC: 2.75%
02/11/2022 09:59:30 AM - EE iteration 875 - KLD: 8.2994, KLDRC: 1.91%
02/11/2022 10:01:44 AM - EE iteration 1000 - KLD: 8.1814, KLDRC: 1.42%
02/11/2022 10:03:58 AM - EE iteration 1125 - KLD: 8.0905, KLDRC: 1.11%
02/11/2022 10:06:12 AM - EE iteration 1250 - KLD: 8.018, KLDRC: 0.9%
02/11/2022 10:06:12 AM - Main iteration learning rate: 64000.0
02/11/2022 10:08:20 AM - Main iteration 125 - KLD: 5.6941, KLDRC: 28.98%
02/11/2022 10:10:32 AM - Main iteration 250 - KLD: 4.7846, KLDRC: 15.97%
02/11/2022 10:12:55 AM - Main iteration 375 - KLD: 4.2811, KLDRC: 10.52%
02/11/2022 10:15:35 AM - Main iteration 500 - KLD: 3.9693, KLDRC: 7.28%
02/11/2022 10:18:31 AM - Main iteration 625 - KLD: 3.7595, KLDRC: 5.29%
02/11/2022 10:21:45 AM - Main iteration 750 - KLD: 3.6053, KLDRC: 4.1%
02/11/2022 10:25:18 AM - Main iteration 875 - KLD: 3.486, KLDRC: 3.31%
02/11/2022 10:29:11 AM - Main iteration 1000 - KLD: 3.389, KLDRC: 2.78%
02/11/2022 10:33:18 AM - Main iteration 1125 - KLD: 3.3088, KLDRC: 2.37%
02/11/2022 10:37:54 AM - Main iteration 1250 - KLD: 3.2404, KLDRC: 2.07%
02/11/2022 10:42:47 AM - Main iteration 1375 - KLD: 3.1817, KLDRC: 1.81%
02/11/2022 10:47:59 AM - Main iteration 1500 - KLD: 3.1292, KLDRC: 1.65%
02/11/2022 10:53:31 AM - Main iteration 1625 - KLD: 3.0829, KLDRC: 1.48%
02/11/2022 10:59:21 AM - Main iteration 1750 - KLD: 3.0406, KLDRC: 1.37%
02/11/2022 11:05:37 AM - Main iteration 1875 - KLD: 3.0021, KLDRC: 1.27%
02/11/2022 11:12:24 AM - Main iteration 2000 - KLD: 2.9682, KLDRC: 1.13%
02/11/2022 11:19:12 AM - Main iteration 2125 - KLD: 2.9366, KLDRC: 1.06%
02/11/2022 11:25:59 AM - Main iteration 2250 - KLD: 2.907, KLDRC: 1.01%
02/11/2022 11:33:15 AM - Main iteration 2375 - KLD: 2.8802, KLDRC: 0.92%
02/11/2022 11:33:15 AM - Finished dimensionality-reduction in 3625 iterations. Final KLD: 2.8802
02/11/2022 11:33:16 AM - Reading annotation.
02/11/2022 11:33:21 AM - Reading embedding coordinates.
02/11/2022 11:33:21 AM - 2857 samples for depth data found.
```

slurm_JobID.output:

```bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Building DAG of jobs...
Creating report...
Missing metadata for file /home/binny_output/binny.done. Maybe metadata was deleted or it was created using an older version of Snakemake. This is a non critical warning.
Downloading resources and rendering HTML.
Report created: report.html.
```

config.mod_default.yaml

```mem:
 # If your HPC resource has a high memory capacity node you can set this to
  # TRUE and specify the amount of memory per core (e.g. if a node has 260 gb of
  # RAM and 10 cores it would be 26).
  big_mem_avail: 0
  big_mem_per_core_gb: 26
  # Memory per core of your computing resource.
  normal_mem_per_core_gb: 100
# Path to a temporary directory to write to.
tmp_dir: tmp
raws:
  # Path to an assembly fasta.
  assembly: "/binny_files/group-1.contigs.fa.gz"
  # Path to a bam file(s) to calculate depth from. Use wildcards for multiple samples, e.g.:
  # "path/to/my/mappings/*.bam" or "path/to/my/mappings/with/*/different/folder/*/structure/*.bam" or "path/to/my/mappings/my_mapping.bam"
  # Leave empty if you have an average depth per contig file to supply to binny.
  metagenomics_alignment: ""
  # Path to an average depth per contig tsv file. Leave empty if you supply a
  # bam file for binny to calculate average contig depth from. First column needs to be the contig ids, subsequent column(s) for depht(s).
  contig_depth: "/binny_files/depth.txt"
# Sample name
sample: "test_10_31_22"
# Path to desired output dir binny should create and store results in.
outputdir: "/home/binny_output"
# Absolute path to put binny dbs in. If left empty they will be put into 'database' in the binny main dir.
db_path: ""
# If you want to use existing environments containing the environments for Snakemake, Prokka
# and/or Mantis you can either input the absolute paths to yaml files or env names here.
# Otherwise, leave empty and binny will take care of the installations.
# If you already have Snakemake in your path set: snakemake_env="in_path".
snakemake_env: ""
prokka_env: ""
mantis_env: ""
# Set path for conda envs to be installed to. By default, they will be put in `conda` in the binny dir.
conda_source: ""
# Input a list, e.g. '2,3,4'.
kmers: '2,3,4'
# Mask potentially disruptive contig regions (e.g. rRNA and CRISPR elements) from k-mer counting
mask_disruptive_sequences: 'True'
# Extract single contig MAGs of at least 90% purity and 92.5% completeness
extract_scmags: 'True'
# Will use coassembly mode, starting with contigs >= 500 bp instead of high threshold, decreasing, if set to 'on' or
# if 'auto' and multiple depth files are detected
# Choose between: 'auto', 'on' , 'off''
coassembly_mode: 'auto'
# Binny prefilters assemblies based on N<X> value to try and take as much information as possible into account,
# while minimizing the amount of noise. Be aware that, depending on the assembly quality, low values as the N<X>
# might results in leaving out a large proportion of the assembly (if the max_cont_length cutoffs are set high as well).
NX_value: 90
# Minimum and maximum contig length. Caps value from NX filtering.
min_cont_length_cutoff: 500  # 500
max_cont_length_cutoff: 1000  # 1000
# Minimum and maximum length of contigs containing CheckM markers. Caps value from NX filtering (initial value is NX_value / 2).
min_cont_length_cutoff_marker: 250  # 250
max_cont_length_cutoff_marker: 400  # 400
# Maximum number of contigs binny uses. If the number of available
# contigs after minimum size filtering exceeds this, binny will
# increase the minimum size threshold until the maximum is reached.
# Prevents use of excessive amounts of memory on large assemblies.
# Default should ensure adequate performance, adjust e.g. according
# to available memory.
max_n_contigs: 1.5e6  # 3.5e5
# Maximum marker set lineage depth to check bin quality with:
# 0: 'domain', 1: 'phylum', 2: 'class', 3: 'order', 4: 'family', 5: 'genus', 6: 'species'
max_marker_lineage_depth_lvl: 5
# Distance metric for opentSNE and HDBSCAN.
distance_metric: 'manhattan'
embedding:
  # Maximum number of binny iterations.
  max_iterations: 50
clustering:
  # Increasing the HDBSCAN cluster selection epsilon beyond 0.5
  # is not advised as it might massively increase run time, but it might
  # help recover fragmented genomes that would be missed with lower settings.
  hdbscan_epsilon_range: '0.250,0.000'
  # Adapted from the HDBSCAN manual: 'Measure of how conservative the
  # clustering should be. With larger values, more points will be declared
  # as noise, and clusters will be restricted to progressively more dense areas.'.
  hdbscan_min_samples_range: '1,5,10' # '1,2,4,6,8'
  # Use depth as additional dimension during the initial clustering.
  include_depth_initial: 'False'
  # Use depth as additional dimension during the main clusterings.
  include_depth_main: 'False'
bin_quality:
  # Minimum value binny will lower completeness to while running.
  min_completeness: 72.5
  # Completeness threshold binny wilt begin with.
  start_completeness: 92.5
  # Minimum purity for bins to be selected.
  purity: 75
write_contig_data: 'True'
```
slurm_simple.config.yaml

```__default__:
  call: "sbatch "
  nodes: "-N 1"
  partition: ""
  qos: "-q primary"
  mem_per_cpu: "--mem-per-cpu "
  runtime: "-t 7-0"
  threads: "-c 1"
  stdout: "-o binny.{rule}.{wildcards}.stdout"
```

VARIABLE_CONFIG

```SNAKEMAKE_VIA_CONDA     true
SNAKEMAKE_EXTRA_ARGUMENTS
LOADING_MODULES
SUBMIT_COMMAND  sbatch -q primary --time=120:00:00 -N 1 -n 1 --mem=15G --output=slurm-%j.out
BIND_JOBS_TO_MAIN       false
NODENAME_VAR    SLURMD_NODENAME
SCHEDULER       slurm_simple
MAX_THREADS     1
```

**Comment by ohickl** [comment]
Hi jp589,

> This time, with four samples I am able to go through the entire process and get a bins directory in the output folder, but no bins.

Does the depth file look fine? E.g. not empty or just zeroes? The assembly is a coassembly of the reads from the 4 samples?

> My next thought was that perhaps I needed to add more samples so...

Could you post the first few rows of the contig depth file? `ValueError: could not convert string to float: 'contigLen'` seems to indicate that there's something wrong (e.g. two header columns maybe?). 

On a side note: I would also leave the `{min,max}_cont_length_cutoff` and `{min,max}_cont_length_cutoff_marker` at the default 2250 for optimal performance (the current commented values listed are old, will be fixed next release), unless you have a clear reason to suspect you need the smaller ones. binny will vary the size anyway during its run to try to optimize the results.
Also, while it might increase performance to increase the `max_marker_lineage_depth_lvl` it will also increase the runtime, especially with the ~3k sample attempt. MIght be more efficient to keep it at 2 for that one.

Best

Oskar

**Comment by jp589** [comment]
Thank you for your prompt response. The depth file is not empty or just zeroes. I am inputting it as a .txt file, but the file is tab delimited. I have attached the first 10 rows of the depth file. Let me know if it looks like there's anything wrong with it.

[depth_head.txt](https://github.com/a-h-b/binny/files/9929618/depth_head.txt)

The assembly I am using is a coassembly of all reads.

I have updated the `{min,max}_cont_length_cutoff` and `{min,max}_cont_length_cutoff_marker` at the defaults of 2250 as you suggest and I have updated the `max_marker_lineage_depth_lvl` to 2, but we are hoping to get species or strain level bins from our data.

Thanks,

jp589

**Comment by ohickl** [comment]
Thanks for the file. Indeed, you need to remove the second and third column, as they are the length and total average depth.
Also, and this seems to be a bug, binny tries to incorporate the header, which causes the crash. It was supposed to auto detect if a table has one or not, I will fix this for the next version. For now you'll have to remove the header row.

I also see that the depth file is mostly zeroes, which might cause problems when emphasizing the depth in coassembly mode. It might cause separation issues since all the contigs will be very similar to each other, distance-wise. You can give it another go (might still be fine, since these first contigs in the file are mostly below 500bp anyway) and, if the results are still much worse than expected you could try to go with `coassembly_mode: 'off'` and see, if that gives you better results.

> but we are hoping to get species or strain level bins from our data.

That should still work fine, depending on the input.

**Comment by jp589** [comment]
Okay, so I've removed the second and third columns as well as the header row like you suggested and it still fails, but for a different reason, which seems to be either the contig names in the depth file or the number of allocated threads.

binny.binny..stdout
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 11
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Thu Nov  3 22:59:47 2022]
Job 0: binny: Running Python Binny.

Activating conda environment: /home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e
Activating conda environment: /home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e

libgomp: Invalid value for environment variable OMP_NUM_THREADS
Traceback (most recent call last):
  File "/home/.snakemake/scripts/tmpij_iootv.binny_main.py", line 157, in <module>
    all_good_bins, contig_data_df_org, min_purity = iterative_embedding(x_contigs, depth_dict, all_good_bins, starting_completeness,
  File "/home/binny/workflow/scripts/binny_functions.py", line 1472, in iterative_embedding
    round_x_depth = np.array([depth_dict[contig] for contig in round_x_contigs])
  File "/home/binny/workflow/scripts/binny_functions.py", line 1472, in <listcomp>
    round_x_depth = np.array([depth_dict[contig] for contig in round_x_contigs])
KeyError: 'k127_2054272 flag=0 multi=91.9963 len=495501'
[Thu Nov  3 23:50:02 2022]
Error in rule binny:
    jobid: 0
    output: /home/binny.done
    log: /home/logs/binning_binny.log (check log file(s) for error message)
    conda-env: /home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e

Traceback (most recent call last):
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/binny/conda/snakemake_env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2460, in run_wrapper
    raise ex
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
    run(
  File "/home/binny/Snakefile", line 668, in __rule_binny
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 1369, in script
    executor.evaluate()
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 582, in execute_script
    self._execute_cmd("{py_exec} {fname:q}", py_exec=py_exec, fname=fname)
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/script.py", line 414, in _execute_cmd
    return shell(
  File "/home/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /home/binny/conda/snakemake_env/bin/activate '/home/binny/conda/48ad8fcdeff72f1a87686f510a50eb8e'; set -euo pipefail;  python /home/.snakemake/scripts/tmpij_iootv.binny_main.py' returned non-zero exit status 1.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

config.mod_default.yaml
```
  big_mem_per_core_gb: 100
  # Memory per core of your computing resource.
  normal_mem_per_core_gb: 100
# Path to a temporary directory to write to.
tmp_dir: tmp
raws:
  # Path to an assembly fasta.
  assembly: "/home/binny_files/group-1.contigs.fa.gz"
  # Path to a bam file(s) to calculate depth from. Use wildcards for multiple samples, e.g.:
  # "path/to/my/mappings/*.bam" or "path/to/my/mappings/with/*/different/folder/*/structure/*.bam" or "path/to/my/mappings/my_mapping.bam"
  # Leave empty if you have an average depth per contig file to supply to binny.
  metagenomics_alignment: ""
  # Path to an average depth per contig tsv file. Leave empty if you supply a
  # bam file for binny to calculate average contig depth from. First column needs to be the contig ids, subsequent column(s) for depht(s).
  contig_depth: "/home/clean.depth.txt"
# Sample name
sample: "test_10_31_22"
# Path to desired output dir binny should create and store results in.
outputdir: "/home/binny_output"
# Absolute path to put binny dbs in. If left empty they will be put into 'database' in the binny main dir.
db_path: ""
# If you want to use existing environments containing the environments for Snakemake, Prokka
# and/or Mantis you can either input the absolute paths to yaml files or env names here.
# Otherwise, leave empty and binny will take care of the installations.
# If you already have Snakemake in your path set: snakemake_env="in_path".
snakemake_env: ""
prokka_env: ""
mantis_env: ""
# Set path for conda envs to be installed to. By default, they will be put in `conda` in the binny dir.
conda_source: ""
# Input a list, e.g. '2,3,4'.
kmers: '2,3,4'
# Mask potentially disruptive contig regions (e.g. rRNA and CRISPR elements) from k-mer counting
mask_disruptive_sequences: 'True'
# Extract single contig MAGs of at least 90% purity and 92.5% completeness
extract_scmags: 'True'
# Will use coassembly mode, starting with contigs >= 500 bp instead of high threshold, decreasing, if set to 'on' or
# if 'auto' and multiple depth files are detected
# Choose between: 'auto', 'on' , 'off''
coassembly_mode: 'auto'
# Binny prefilters assemblies based on N<X> value to try and take as much information as possible into account,
# while minimizing the amount of noise. Be aware that, depending on the assembly quality, low values as the N<X>
# might results in leaving out a large proportion of the assembly (if the max_cont_length cutoffs are set high as well).
NX_value: 90
# Minimum and maximum contig length. Caps value from NX filtering.
min_cont_length_cutoff: 2250  # 500
max_cont_length_cutoff: 2250  # 1000
# Minimum and maximum length of contigs containing CheckM markers. Caps value from NX filtering (initial value is NX_value / 2).
min_cont_length_cutoff_marker: 250  # 250
max_cont_length_cutoff_marker: 400  # 400
# Maximum number of contigs binny uses. If the number of available
# contigs after minimum size filtering exceeds this, binny will
# increase the minimum size threshold until the maximum is reached.
# Prevents use of excessive amounts of memory on large assemblies.
# Default should ensure adequate performance, adjust e.g. according
# to available memory.
max_n_contigs: 1.5e6  # 3.5e5
# Maximum marker set lineage depth to check bin quality with:
# 0: 'domain', 1: 'phylum', 2: 'class', 3: 'order', 4: 'family', 5: 'genus', 6: 'species'
max_marker_lineage_depth_lvl: 2
# Distance metric for opentSNE and HDBSCAN.
distance_metric: 'manhattan'
embedding:
  # Maximum number of binny iterations.
  max_iterations: 50
clustering:
  # Increasing the HDBSCAN cluster selection epsilon beyond 0.5
  # is not advised as it might massively increase run time, but it might
  # help recover fragmented genomes that would be missed with lower settings.
  hdbscan_epsilon_range: '0.250,0.000'
  # Adapted from the HDBSCAN manual: 'Measure of how conservative the
  # clustering should be. With larger values, more points will be declared
  # as noise, and clusters will be restricted to progressively more dense areas.'.
  hdbscan_min_samples_range: '1,5,10' # '1,2,4,6,8'
  # Use depth as additional dimension during the initial clustering.
  include_depth_initial: 'False'
  # Use depth as additional dimension during the main clusterings.
  include_depth_main: 'False'
bin_quality:
  # Minimum value binny will lower completeness to while running.
  min_completeness: 72.5
  # Completeness threshold binny wilt begin with.
  start_completeness: 92.5
  # Minimum purity for bins to be selected.
  purity: 75
write_contig_data: 'True'
```

binning_binny.log
```
03/11/2022 11:00:46 PM - Starting Binny run for sample test_10_31_22.
03/11/2022 11:01:13 PM - Looking for single contig bins.
03/11/2022 11:01:49 PM - Found 0 single contig bins.
03/11/2022 11:01:49 PM - Calculating N90
03/11/2022 11:01:50 PM - N90 is 541, with scMAGs would be 541.
03/11/2022 11:01:58 PM - Masking potentially disruptive sequences from k-mer counting.
03/11/2022 11:02:02 PM - Calculating k-mer frequencies of sizes: 2, 3, 4.
03/11/2022 11:46:08 PM - K-mer frequency matrix created in 2649s.
03/11/2022 11:49:31 PM - Using single sample mode.
03/11/2022 11:49:37 PM - Running with 1458430 contigs. Filtered 0 contigs using a min contig size of 250 to stay below 1500000.0 contigs
```

Any help getting this to finally finish would be much appreciated.

Thanks,

jp589

**Comment by ohickl** [comment]
This is probably due to the fact that there are spaces in either the contig ID of the fasta or depth table, or both. For some reason some assemblers/pipelines put non-standard characters in the contig headers, e.g. `k127_2054272 flag=0 multi=91.9963 len=495501` should either have something like `_` instead of the spaces or just be `k127_2054272`. Could you check, if the contig IDs in `assembly.formatted.fa` and `assembly.contig_depth.txt` in `path/to/my/binny/output/intermediary` are identical (or in the input files)?
I'd also change
```
min_cont_length_cutoff_marker: 250  # 250
max_cont_length_cutoff_marker: 400  # 400
```
to `2250` as well in the config.

**Comment by ohickl** [comment]
Sorry for the delay, was ill.
That is very strange. Could be that some intermediary files that i didn't think of still have the long IDs. I would delete the entire output and rerun using fixed input files. Let me know if there's still problems then.

**Comment by jp589** [comment]
Hello,

After several months of trying to get this to work, I was finally able to produce bins. I had to, as you suggested, ensure that the headers in the assembly file matched the row headers in the depth file exactly and furthermore, that the depth file was tab delimited. Once those were fixed, binny was able to complete the run.

Thank you very much for your help!

jp589

**Comment by ohickl** [comment]
Great to hear! Let us know, if you have any more problems/questions!
