### ISSUE TITLE
snakemake.exceptions.CreateCondaEnvironmentException

### ISSUE THREAD

**Issue by MiracleEaTu** [a-h-b/binny#63]
When I was trying to install binny using default settings: `./binny -i config/config.init.yaml` I got this error message:

```bash
Full Traceback (most recent call last):
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 590, in create
    out = create_env(env_file, filetype="yaml")
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 552, in create_env
    out = shell.check_output(
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/shell.py", line 63, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mamba env create --quiet --file "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_.yaml" --prefix "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_"' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/__init__.py", line 736, in snakemake
    success = workflow.execute(
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/workflow.py", line 924, in execute
    dag.create_conda_envs(
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/dag.py", line 319, in create_conda_envs
    env.create(dryrun)
  File "/home/qijie/binny/conda/snakemake_env/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 609, in create
    raise CreateCondaEnvironmentException(
snakemake.exceptions.CreateCondaEnvironmentException: Could not create conda environment from /home/qijie/binny/workflow/envs/binny_linux.yaml:
Command:
mamba env create --quiet --file "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_.yaml" --prefix "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_"
Output:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.


CreateCondaEnvironmentException:
Could not create conda environment from /home/qijie/binny/workflow/envs/binny_linux.yaml:
Command:
mamba env create --quiet --file "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_.yaml" --prefix "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_"
Output:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

unlocking
removing lock
removing lock
removed all locks
```

Please advise how to install binny correctly, thank you!

**Comment by MiracleEaTu** [comment]
And on the other hand, if I manually run `mamba env create --quiet --file "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_.yaml" --prefix "/home/qijie/binny/conda/5a076611065aff8cc31a351d4096a416_"`, It worked perfectly.. Very weird and the same problem showed up in two separate computers..

**Comment by ohickl** [comment]
Hi,

Sorry for the delay! If you're still having trouble, you can try the following:

    micromamba create --prefix <path/to/my/local_tools>/binny bioconda::binny

or

    micromamba create -n binny bioconda::binny

Alternatively, you can use conda or mamba instead of micromamba if you have either installed.

Best,
Oskar

**Comment by MiracleEaTu** [comment]
Thank you Oskar!

Now I have the binny usage showing like this: 
```
usage: binny [-h] (-a ASSEMBLY | -s) [-b [BAM ...] | --contig_depth CONTIG_DEPTH] [-o OUTPUTDIR] [--sample SAMPLE]
             [--tmp_dir TMP_DIR] [-t THREADS] [--big_mem_avail] [--big_mem_per_core_gb BIG_MEM_PER_CORE_GB]
             [--normal_mem_per_core_gb NORMAL_MEM_PER_CORE_GB] [-c CONFIG_FILE] [-m] [-csc CLUSTER_SUBMISSION_COMMAND]
             [-spp SCHEDULER_PRESET_PATH] [-jn JOB_NAME] [-r] [-d] [-u] [-f] [--db_path DB_PATH] [--kmers KMERS]
             [--mask_disruptive_sequences] [--extract_scmags] [--coassembly_mode {auto,on,off}] [--NX_value NX_VALUE]
             [--min_cont_length_cutoff MIN_CONT_LENGTH_CUTOFF] [--max_cont_length_cutoff MAX_CONT_LENGTH_CUTOFF]
             [--min_cont_length_cutoff_marker MIN_CONT_LENGTH_CUTOFF_MARKER]
             [--max_cont_length_cutoff_marker MAX_CONT_LENGTH_CUTOFF_MARKER] [--max_n_contigs MAX_N_CONTIGS]
             [--max_marker_lineage_depth_lvl {0,1,2,3,4,5,6}]
             [--distance_metric {cityblock,cosine,euclidean,haversine,l1,l2,manhattan,nan_euclidean}]
             [--max_iterations MAX_ITERATIONS] [--hdbscan_epsilon_range HDBSCAN_EPSILON_RANGE]
             [--hdbscan_min_samples_range HDBSCAN_MIN_SAMPLES_RANGE] [--include_depth_initial] [--include_depth_main]
             [--min_completeness MIN_COMPLETENESS] [--start_completeness START_COMPLETENESS] [--purity PURITY]
             [--write_contig_data]
```
Does it means a `config.yml` is no longer needed for binny? I can just add parameters in the command lines? 
Many thanks !

Best,
Qijie

**Comment by ohickl** [comment]
You should be able to use both. A config file using `-c <config.yam>` or any of the params directly

**Comment by MiracleEaTu** [comment]
Thank you Oskar!!
